name: Github Page CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci /home/runner/work/personal-blog/personal-blog/Front
      - run: npm --prefix /Front run build


  push:
    name: Push to Github Page repo
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pushes to Github repository
        uses: Bingsu-kun/github-page-ci-for-react@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          destination-github-username: 'Bingsu-kun'
          user-email: icetime963@gmail.com
          user-name: Hephai